### ISSUE TITLE
c3-0711a 에서 모호한 statement

### ISSUE THREAD

**Issue by jc01rho** [ajouatom/apilot#15]
https://github.com/ajouatom/apilot/blob/fccf6baa70262e3665849efda04d617dcd078e5e/selfdrive/controls/lib/desire_helper.py#L259C34-L259C34

링크의 statement가 assign인지, conditional expression 의 오기인지 혼동이 오도록 작성되어있습니다 ^^;

**Comment by jc01rho** [comment]
desire_helper.py 의 259 라인 입니다.

**Comment by ajouatom** [comment]
급하게 desire_helper.py를 몽땅 새로 수정하다보니... 
오타가 있었네요..

감사합니다...
