### ISSUE TITLE
조향 학습관련내용 초기화방법 질의드립니다.

### ISSUE THREAD

**Issue by jc01rho** [ajouatom/apilot#16]
안녕하세요.

다른분들과 조향관련 콤마내 ui 설정은 일치시켰음에도 조향관련 경험이 다소 차이가나는것같아 
이전 다른 저장소 설치의 잔재 혹은 조향관련학습(?) 내용을 밀어내고싶습니다.

관련 정보를 이디서읻을수있을까요?

**Comment by ajouatom** [comment]
ssh연결후.... 

/data/params/d/LiveTorqueParameters  를 삭제하면 될것 같습니다...


하지만...

개인적으로는 학습이 잘 안맞는듯하여... 

조향학습을 사용하지 않고..

TorqueCustom : 1
TorqueAccelFactor: XXX
TroqueFriction: XXX

이것을 차량에 맞게 입력하여 사용합니다.

또한, Live SteerRatio도  잘 맞지 않는듯하여..

"SteerRatio적용" 값을 수동으로 입력하여 사용중입니다.... 
(이값으로 조정하면 오버/언더 스티어를 쉽게 잡을수 있습니다)


전 이 값들을 수동으로 입력하여 사용하는데... 매우 만족스럽습니다...

**Comment by jc01rho** [comment]
감사합니다 :)
