### ISSUE TITLE
No stop resume for Genesis DH (2015-2016 Genesis)

### ISSUE THREAD

**Issue by Donfyffe** [ajouatom/apilot#26]
Using neokii or opkr I have to use Standstill Resume Alternative.

**Comment by ajouatom** [comment]
> Using neokii or opkr I have to use Standstill Resume Alternative.

please test "c3-dh-autoresume"  branch

and feedback please~~~

**Comment by Donfyffe** [comment]
Thanks, will test later today and let you know. Can Waze work for speed limit control with apilot, I currently use waze internal with opkr C2 & waze external C3 ? Mappy does not work in USA.

**Comment by Donfyffe** [comment]
No good, got " Controls Unresponsive"
![16977571761067311758262049383207](https://github.com/ajouatom/apilot/assets/60390773/7d6ba9e7-f654-483d-b531-58f5a90b32ba)

**Comment by Donfyffe** [comment]
This happens when stop resume behind lead car should happen

**Comment by ajouatom** [comment]
I just made a modification to c3-master related to this.
I don't have much experience with testing, so I'll give it a try and hope for some feedback.

And, if the above error occurs,

I wish you could tell me what error is occurring with a command like "tmux a".

**Comment by Donfyffe** [comment]
Sorry I will be away for a while so I wont be able to this until I return in a few days. Thanks.
