### ISSUE TITLE
Max speed and other info display in metric

### ISSUE THREAD

**Issue by Donfyffe** [ajouatom/apilot#27]
Although my metric toggle is turned off in Toggles menu, the max speed and other info display in metric on c3 driving screen, although the car current speed shows correct MPH speed on driving screen, so I have a mix of imperial & metric speed display.
![New Bitmap Image](https://github.com/ajouatom/apilot/assets/60390773/382e9dfa-8a32-4192-b325-4380d7902cd6)

**Comment by ajouatom** [comment]
> Although my metric toggle is turned off in Toggles menu, the max speed and other info display in metric on c3 driving screen, although the car current speed shows correct MPH speed on driving screen, so I have a mix of imperial & metric speed display. ![New Bitmap Image](https://user-images.githubusercontent.com/60390773/276604677-382e9dfa-8a32-4192-b325-4380d7902cd6.png)

I just made a modification to c3-master related to this.
I don't have much experience with testing, so I'll give it a try and hope for some feedback.
