### ISSUE TITLE
차선변경시 차간거리 2.0 고정 문제

### ISSUE THREAD

**Issue by nara1111** [ajouatom/apilot#34]
안녕하세요,
67eb79f commit 사용중입니다.

고속도로 등에서 차선변경을 하거나, 또는 추적중이던 앞차가 차선변경을 하여 차로가 빌 경우
차간거리가 2.0으로 고정되어 속도가 급감속되는 현상이 있습니다.

왼쪽 물결표시 아래에 빨간색 거리가 표시되는거보면 차간거리 추적은 되는듯 한데, 이상하여 리포트 합니다.

차량은 넥쏘이고, radar on, vision mix 사용중입니다.

**Comment by ajouatom** [comment]
안녕하세요?

물결포시 밑외. 빨간숫자가나오는건 네비속도제한입니다
노란색은 커브제한속도입니다

빨간색이나왔다면
어떤이유인지 속도제한구역인듯한데

이런증상시 화면촬엉이나 늑화부타드립니다

차간거리 2미터는 잘모르는증상이네요

2023년 11월 21일 (화) 오후 6:36, HAN, Sang-uk ***@***.***>님이 작성:

**Comment by nara1111** [comment]
안녕하세요,
운전 중에 어떻게 녹화해야할지 몰라서 우선 녹화해 둔 버전 올려드립니다.
내일 다시 시도해보겠습니다.

https://youtube.com/shorts/sIFKuEnZ7H8?si=ncTwrGBnSLXfv4XG

**Comment by nara1111** [comment]
안녕하세요, 오늘은 4.0입니다 ㅎㅎㅎ

핵심은 앞에 차가 있다가 전방에서 사라지면 4.0으로 고정되고
https://youtube.com/shorts/lQ7lXNavg5c?si=9c9_8rtXiA5EKKlD

이후에 지속적으로 4.0으로 고정되다가 앞 차가 보이면 다시 차간거리를 잡습니다.
https://youtube.com/shorts/ghX2RacsCbo?si=tODf5q8rw3OBUReE

앞에 차가 없으니 default 값으로 회귀되는 거라고 볼 수는 있는데 문제는 크루즈 상태에서 감속을 계속 합니다. (영상에서는 촬영 위해 크루즈를 껐고 수동으로 엑셀을 밟아 가고 있습니다.)

시내도로에서는 그나마 괜찮은데 고속도로에서는 이 문제 때문에 켜고 있을 수가 없네요.

**Comment by ajouatom** [comment]
2.0, 4.0 이상한 현상이네요... 
얼마전 수정한... 레이더루틴에 문제가 있는건지..

SCC레이더와 레이더트랙의 레이더와 통합하는 과정에 문제가 있는듯 보입니다..

저에게는 증상이 안나타나서...
해당 로그를 보면 좋을것 같은데.. 혹시 받아주실수 있나요?

MobaXterm등을 이용하여 접속하여,

/data/media/0/realdata

에서 관련시간의 영상을 찾아 ts영상파일과 rlog를 압축해서 보내주시면 됩니다... 이메일로...

**Comment by ajouatom** [comment]
아~~ 이제 봤네요..
SCC배선개조없이 레이더트랙만 사용하는 경우군요...

제가 시험을 안해본것이고... 
코딩할때 처리를 안했기때문에... 문제가 있을듯하네요.. 수정할께요.. ㅎㅎ

**Comment by ajouatom** [comment]
수정완료... 

c3-master

이증상은 시동걸때 앞에 차가 있었으면, 그때 값이 계속유지되어 나타나는 증상입니다..
전방에 차가 없을때 시동을 걸고 인게이지 하면 증상이 사라질것으로 보이긴합니다...

하지만 수정은 완료하였습니다....

**Comment by nara1111** [comment]
안녕하세요,
네네. 안 그래도 다들 배선개조까지 해야 차간거리까지 잘 잡힌다고 말씀은 해주셔서 준비는 해두고 있는데
도저히 내릴 엄두가 안 나서 차일피일 미루다 날이 추워졌네요.
사실 차가 없을때 시동을 건다...는게 아파트에서는 불가능한 일이 아닐까 싶긴 해서 얼른 배선개조도 해야겠습니다.

수정해주신 브랜치로 적용해보겠습니다!

**Comment by ajouatom** [comment]
배선개조와 차간거리는 관련이 없습니다.
다만 배선개조를 하면, SCC모듈의 기능중 AEB기능을 활용할 수 있습니다.

레이더 트랙이 가능한 차량은 배선개조가 그닥 필요없다고 생각듭니다..
AEB만큼 오파가 어느정도 잘해주니깐요..

**Comment by nara1111** [comment]
그렇군요. 카페에서 배선개조시 차간거리 개선된다는 댓글을 봐서 그런가보다 했는데 또 상관이 없나보군요.

수정된 브랜치로 적용하고 해당 이슈 사라졌습니다! 앞차 못보고 달려들었다가 서면서 울컥거리는 증상이 있는데 이건 세팅을 좀 만져봐야겠네요.

감사합니다!
